config/routes.rb
BlogAdmin::Application.routes.draw do

  resources :joint2s

  resources :joints

  resources :brevets

  resources :pers

  resources :appointments

  resources :patients

  resources :physicians

  resources :personnees

  resources :fonctionns

  resources :personnes

  resources :fonctions

  resources :campaigns

  resources :accounts

  resources :grades

  resources :catgrades

  devise_for :users
  
  mount RailsAdmin::Engine => '', as: 'rails_admin'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    case user.profile
    when 'supervisor'
		can :manage, :all
    when 'superuser'
		#can :access, :rails_admin
		#can :dashboard
		can :manage, :all
		cannot :manage, [User]
	when 'visitor'
		can :access, :rails_admin
		can :dashboard
		#can :read, Blog::Post
		#can :read, Blog::Comment
		can :read, :all
		cannot :read, [User]

    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :appointment_date, :patient_id, :physician_id
  belongs_to :physician
  belongs_to :patient
end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/brevet.rb
class Brevet < ActiveRecord::Base
  attr_accessible :name
  has_many :joint2s
  has_many :pers, :through => :joint2s
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :account
end

app/models/catgrade.rb
class Catgrade < ActiveRecord::Base
end

app/models/fonction.rb
class Fonction < ActiveRecord::Base
end

app/models/fonctionn.rb
class Fonctionn < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :catgrade
end

app/models/joint2.rb
class Joint2 < ActiveRecord::Base
  attr_accessible :appointment_date, :per_id, :brevet_id, :name
  belongs_to :per
  belongs_to :brevet
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :name
  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/per.rb
class Per < ActiveRecord::Base
  attr_accessible :name
  has_many :joint2s
  has_many :brevets, :through => :joint2s
end

app/models/personne.rb
class Personne < ActiveRecord::Base
  belongs_to :fonction
end

app/models/personnee.rb
class Personnee < ActiveRecord::Base
  belongs_to :fonctionn
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  attr_accessible :name
  has_many :appointments
  has_many :patients, :through => :appointments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    email.try(:split, '@').try(:first).try(:humanize)
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render action: 'show', status: :created, location: @grade }
      else
        format.html { render action: 'new' }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:libgrade, :catgrade_id)
    end
end

app/helpers/brevets_helper.rb
module BrevetsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/joint2s_helper.rb
module Joint2sHelper
end

app/helpers/joints_helper.rb
module JointsHelper
end

app/helpers/pers_helper.rb
module PersHelper
end

app/views/grades/_form.html.slim
= form_for @grade do |f|
  - if @grade.errors.any?
    #error_explanation
      h2 = "#{pluralize(@grade.errors.count, "error")} prohibited this grade from being saved:"
      ul
        - @grade.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :libgrade
    = f.text_field :libgrade
  .field
    = f.label :catgrade
    = f.text_field :catgrade
  .actions = f.submit 'Save'

app/views/grades/edit.html.slim
h1 Editing grade

== render 'form'

= link_to 'Show', @grade
'|
= link_to 'Back', grades_path

app/views/grades/index.html.slim
h1 Listing grades

table
  tr
    th Libgrade
    th Catgrade
    th
    th
    th

  - @grades.each do |grade|
    tr
      td = grade.libgrade
      td = grade.catgrade
      td = link_to 'Show', grade
      td = link_to 'Edit', edit_grade_path(grade)
      td = link_to 'Destroy', grade, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Grade', new_grade_path

app/views/grades/new.html.slim
h1 New grade

== render 'form'

= link_to 'Back', grades_path

app/views/grades/show.html.slim
p#notice = notice

p
  strong Libgrade:
  = @grade.libgrade
p
  strong Catgrade:
  = @grade.catgrade

= link_to 'Edit', edit_grade_path(@grade)
'|
= link_to 'Back', grades_path