config/routes.rb
BlogAdmin::Application.routes.draw do

  resources :joint2s

  resources :joints

  resources :brevets

  resources :pers

  resources :appointments

  resources :patients

  resources :physicians

  resources :personnees

  resources :fonctionns

  resources :personnes

  resources :fonctions

  resources :campaigns

  resources :accounts

  resources :grades

  resources :catgrades

  devise_for :users
  
  mount RailsAdmin::Engine => '', as: 'rails_admin'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    case user.profile
    when 'supervisor'
		can :manage, :all
    when 'superuser'
		#can :access, :rails_admin
		#can :dashboard
		can :manage, :all
		cannot :manage, [User]
	when 'visitor'
		can :access, :rails_admin
		can :dashboard
		#can :read, Blog::Post
		#can :read, Blog::Comment
		can :read, :all
		cannot :read, [User]

    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :appointment_date, :patient_id, :physician_id
  belongs_to :physician
  belongs_to :patient
end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/brevet.rb
class Brevet < ActiveRecord::Base
  attr_accessible :name
  has_many :joint2s
  has_many :pers, :through => :joint2s
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :account
end

app/models/catgrade.rb
class Catgrade < ActiveRecord::Base
end

app/models/fonction.rb
class Fonction < ActiveRecord::Base
end

app/models/fonctionn.rb
class Fonctionn < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :catgrade
end

app/models/joint2.rb
class Joint2 < ActiveRecord::Base
  attr_accessible :appointment_date, :per_id, :brevet_id, :name
  belongs_to :per
  belongs_to :brevet
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :name
  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/per.rb
class Per < ActiveRecord::Base
  attr_accessible :name
  has_many :joint2s
  has_many :brevets, :through => :joint2s
end

app/models/personne.rb
class Personne < ActiveRecord::Base
  belongs_to :fonction
end

app/models/personnee.rb
class Personnee < ActiveRecord::Base
  belongs_to :fonctionn
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  attr_accessible :name
  has_many :appointments
  has_many :patients, :through => :appointments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    email.try(:split, '@').try(:first).try(:humanize)
  end
end

app/controllers/personnes_controller.rb
class PersonnesController < ApplicationController
  before_action :set_personne, only: [:show, :edit, :update, :destroy]

  # GET /personnes
  # GET /personnes.json
  def index
    @personnes = Personne.all
  end

  # GET /personnes/1
  # GET /personnes/1.json
  def show
  end

  # GET /personnes/new
  def new
    @personne = Personne.new
  end

  # GET /personnes/1/edit
  def edit
  end

  # POST /personnes
  # POST /personnes.json
  def create
    @personne = Personne.new(personne_params)

    respond_to do |format|
      if @personne.save
        format.html { redirect_to @personne, notice: 'Personne was successfully created.' }
        format.json { render action: 'show', status: :created, location: @personne }
      else
        format.html { render action: 'new' }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnes/1
  # PATCH/PUT /personnes/1.json
  def update
    respond_to do |format|
      if @personne.update(personne_params)
        format.html { redirect_to @personne, notice: 'Personne was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnes/1
  # DELETE /personnes/1.json
  def destroy
    @personne.destroy
    respond_to do |format|
      format.html { redirect_to personnes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personne
      @personne = Personne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personne_params
      params.require(:personne).permit(:nom, :fonction_id)
    end
end

app/helpers/brevets_helper.rb
module BrevetsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/joints_helper.rb
module JointsHelper
end

app/helpers/pers_helper.rb
module PersHelper
end

app/helpers/personnes_helper.rb
module PersonnesHelper
end

app/views/personnes/_form.html.slim
= form_for @personne do |f|
  - if @personne.errors.any?
    #error_explanation
      h2 = "#{pluralize(@personne.errors.count, "error")} prohibited this personne from being saved:"
      ul
        - @personne.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :nom
    = f.text_field :nom
  .field
    = f.label :fonction
    = f.text_field :fonction
  .actions = f.submit 'Save'

app/views/personnes/edit.html.slim
h1 Editing personne

== render 'form'

= link_to 'Show', @personne
'|
= link_to 'Back', personnes_path

app/views/personnes/index.html.slim
h1 Listing personnes

table
  tr
    th Nom
    th Fonction
    th
    th
    th

  - @personnes.each do |personne|
    tr
      td = personne.nom
      td = personne.fonction
      td = link_to 'Show', personne
      td = link_to 'Edit', edit_personne_path(personne)
      td = link_to 'Destroy', personne, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Personne', new_personne_path

app/views/personnes/new.html.slim
h1 New personne

== render 'form'

= link_to 'Back', personnes_path

app/views/personnes/show.html.slim
p#notice = notice

p
  strong Nom:
  = @personne.nom
p
  strong Fonction:
  = @personne.fonction

= link_to 'Edit', edit_personne_path(@personne)
'|
= link_to 'Back', personnes_path