config/routes.rb
BlogAdmin::Application.routes.draw do

  resources :joint2s

  resources :joints

  resources :brevets

  resources :pers

  resources :appointments

  resources :patients

  resources :physicians

  resources :personnees

  resources :fonctionns

  resources :personnes

  resources :fonctions

  resources :campaigns

  resources :accounts

  resources :grades

  resources :catgrades

  devise_for :users
  
  mount RailsAdmin::Engine => '', as: 'rails_admin'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    case user.profile
    when 'supervisor'
		can :manage, :all
    when 'superuser'
		#can :access, :rails_admin
		#can :dashboard
		can :manage, :all
		cannot :manage, [User]
	when 'visitor'
		can :access, :rails_admin
		can :dashboard
		#can :read, Blog::Post
		#can :read, Blog::Comment
		can :read, :all
		cannot :read, [User]

    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :appointment_date, :patient_id, :physician_id
  belongs_to :physician
  belongs_to :patient
end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/brevet.rb
class Brevet < ActiveRecord::Base
  attr_accessible :name
  has_many :joint2s
  has_many :pers, :through => :joint2s
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :account
end

app/models/catgrade.rb
class Catgrade < ActiveRecord::Base
end

app/models/fonction.rb
class Fonction < ActiveRecord::Base
end

app/models/fonctionn.rb
class Fonctionn < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :catgrade
end

app/models/joint2.rb
class Joint2 < ActiveRecord::Base
  attr_accessible :appointment_date, :per_id, :brevet_id, :name
  belongs_to :per
  belongs_to :brevet
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :name
  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/per.rb
class Per < ActiveRecord::Base
  attr_accessible :name
  has_many :joint2s
  has_many :brevets, :through => :joint2s
end

app/models/personne.rb
class Personne < ActiveRecord::Base
  belongs_to :fonction
end

app/models/personnee.rb
class Personnee < ActiveRecord::Base
  belongs_to :fonctionn
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  attr_accessible :name
  has_many :appointments
  has_many :patients, :through => :appointments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    email.try(:split, '@').try(:first).try(:humanize)
  end
end

app/controllers/personnees_controller.rb
class PersonneesController < ApplicationController
  before_action :set_personnee, only: [:show, :edit, :update, :destroy]

  # GET /personnees
  # GET /personnees.json
  def index
    @personnees = Personnee.all
  end

  # GET /personnees/1
  # GET /personnees/1.json
  def show
  end

  # GET /personnees/new
  def new
    @personnee = Personnee.new
  end

  # GET /personnees/1/edit
  def edit
  end

  # POST /personnees
  # POST /personnees.json
  def create
    @personnee = Personnee.new(personnee_params)

    respond_to do |format|
      if @personnee.save
        format.html { redirect_to @personnee, notice: 'Personnee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @personnee }
      else
        format.html { render action: 'new' }
        format.json { render json: @personnee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnees/1
  # PATCH/PUT /personnees/1.json
  def update
    respond_to do |format|
      if @personnee.update(personnee_params)
        format.html { redirect_to @personnee, notice: 'Personnee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @personnee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnees/1
  # DELETE /personnees/1.json
  def destroy
    @personnee.destroy
    respond_to do |format|
      format.html { redirect_to personnees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personnee
      @personnee = Personnee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personnee_params
      params.require(:personnee).permit(:name, :fonctionn_id)
    end
end

app/helpers/brevets_helper.rb
module BrevetsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/joints_helper.rb
module JointsHelper
end

app/helpers/pers_helper.rb
module PersHelper
end

app/helpers/personnees_helper.rb
module PersonneesHelper
end

app/views/personnees/_form.html.slim
= form_for @personnee do |f|
  - if @personnee.errors.any?
    #error_explanation
      h2 = "#{pluralize(@personnee.errors.count, "error")} prohibited this personnee from being saved:"
      ul
        - @personnee.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :fonctionn
    = f.text_field :fonctionn
  .actions = f.submit 'Save'

app/views/personnees/edit.html.slim
h1 Editing personnee

== render 'form'

= link_to 'Show', @personnee
'|
= link_to 'Back', personnees_path

app/views/personnees/index.html.slim
h1 Listing personnees

table
  tr
    th Name
    th Fonctionn
    th
    th
    th

  - @personnees.each do |personnee|
    tr
      td = personnee.name
      td = personnee.fonctionn
      td = link_to 'Show', personnee
      td = link_to 'Edit', edit_personnee_path(personnee)
      td = link_to 'Destroy', personnee, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Personnee', new_personnee_path

app/views/personnees/new.html.slim
h1 New personnee

== render 'form'

= link_to 'Back', personnees_path

app/views/personnees/show.html.slim
p#notice = notice

p
  strong Name:
  = @personnee.name
p
  strong Fonctionn:
  = @personnee.fonctionn

= link_to 'Edit', edit_personnee_path(@personnee)
'|
= link_to 'Back', personnees_path