config/routes.rb
BlogAdmin::Application.routes.draw do

  resources :joint2s

  resources :joints

  resources :brevets

  resources :pers

  resources :appointments

  resources :patients

  resources :physicians

  resources :personnees

  resources :fonctionns

  resources :personnes

  resources :fonctions

  resources :campaigns

  resources :accounts

  resources :grades

  resources :catgrades

  devise_for :users
  
  mount RailsAdmin::Engine => '', as: 'rails_admin'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    case user.profile
    when 'supervisor'
		can :manage, :all
    when 'superuser'
		#can :access, :rails_admin
		#can :dashboard
		can :manage, :all
		cannot :manage, [User]
	when 'visitor'
		can :access, :rails_admin
		can :dashboard
		#can :read, Blog::Post
		#can :read, Blog::Comment
		can :read, :all
		cannot :read, [User]

    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :appointment_date, :patient_id, :physician_id
  belongs_to :physician
  belongs_to :patient
end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/brevet.rb
class Brevet < ActiveRecord::Base
  attr_accessible :name
  has_many :joint2s
  has_many :pers, :through => :joint2s
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :account
end

app/models/catgrade.rb
class Catgrade < ActiveRecord::Base
end

app/models/fonction.rb
class Fonction < ActiveRecord::Base
end

app/models/fonctionn.rb
class Fonctionn < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :catgrade
end

app/models/joint2.rb
class Joint2 < ActiveRecord::Base
  attr_accessible :appointment_date, :per_id, :brevet_id, :name
  belongs_to :per
  belongs_to :brevet
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :name
  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/per.rb
class Per < ActiveRecord::Base
  attr_accessible :name
  has_many :joint2s
  has_many :brevets, :through => :joint2s
end

app/models/personne.rb
class Personne < ActiveRecord::Base
  belongs_to :fonction
end

app/models/personnee.rb
class Personnee < ActiveRecord::Base
  belongs_to :fonctionn
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  attr_accessible :name
  has_many :appointments
  has_many :patients, :through => :appointments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    email.try(:split, '@').try(:first).try(:humanize)
  end
end

app/controllers/joints_controller.rb
class JointsController < ApplicationController
  before_action :set_joint, only: [:show, :edit, :update, :destroy]

  # GET /joints
  # GET /joints.json
  def index
    @joints = Joint.all
  end

  # GET /joints/1
  # GET /joints/1.json
  def show
  end

  # GET /joints/new
  def new
    @joint = Joint.new
  end

  # GET /joints/1/edit
  def edit
  end

  # POST /joints
  # POST /joints.json
  def create
    @joint = Joint.new(joint_params)

    respond_to do |format|
      if @joint.save
        format.html { redirect_to @joint, notice: 'Joint was successfully created.' }
        format.json { render action: 'show', status: :created, location: @joint }
      else
        format.html { render action: 'new' }
        format.json { render json: @joint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joints/1
  # PATCH/PUT /joints/1.json
  def update
    respond_to do |format|
      if @joint.update(joint_params)
        format.html { redirect_to @joint, notice: 'Joint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @joint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joints/1
  # DELETE /joints/1.json
  def destroy
    @joint.destroy
    respond_to do |format|
      format.html { redirect_to joints_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joint
      @joint = Joint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def joint_params
      params.require(:joint).permit(:per_id, :brevet_id, :appointment_date, :name)
    end
end

app/helpers/brevets_helper.rb
module BrevetsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/joints_helper.rb
module JointsHelper
end

app/helpers/pers_helper.rb
module PersHelper
end

app/views/joints/_form.html.slim
= form_for @joint do |f|
  - if @joint.errors.any?
    #error_explanation
      h2 = "#{pluralize(@joint.errors.count, "error")} prohibited this joint from being saved:"
      ul
        - @joint.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :per_id
    = f.number_field :per_id
  .field
    = f.label :brevet_id
    = f.number_field :brevet_id
  .field
    = f.label :appointment_date
    = f.datetime_select :appointment_date
  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit 'Save'

app/views/joints/edit.html.slim
h1 Editing joint

== render 'form'

= link_to 'Show', @joint
'|
= link_to 'Back', joints_path

app/views/joints/index.html.slim
h1 Listing joints

table
  tr
    th Per
    th Brevet
    th Appointment date
    th Name
    th
    th
    th

  - @joints.each do |joint|
    tr
      td = joint.per_id
      td = joint.brevet_id
      td = joint.appointment_date
      td = joint.name
      td = link_to 'Show', joint
      td = link_to 'Edit', edit_joint_path(joint)
      td = link_to 'Destroy', joint, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Joint', new_joint_path

app/views/joints/new.html.slim
h1 New joint

== render 'form'

= link_to 'Back', joints_path

app/views/joints/show.html.slim
p#notice = notice

p
  strong Per:
  = @joint.per_id
p
  strong Brevet:
  = @joint.brevet_id
p
  strong Appointment date:
  = @joint.appointment_date
p
  strong Name:
  = @joint.name

= link_to 'Edit', edit_joint_path(@joint)
'|
= link_to 'Back', joints_path